name: CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Security scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Build Docker image
        run: docker build -t my-app .

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: my-app
          severity: HIGH,CRITICAL
          exit-code: 1
